### ISSUE TITLE
Error: Unsupported function signature format. Parameter destruction

### ISSUE THREAD

**Issue by bitspook** [gajus/canonical#14]
I am getting this error in files which has jsdoc defined like this:

``` js
/**
 * My awesome function
 * @param {Object} latLng
 * @property {number} lat
 * @property {number} lng
 *
 * @returns {Promise}
 */
```

It was working fine earlier. This error will of course go away when(/if) we remove jsdoc validations (in favour of typecheck).
The complete error is:

```
Unhandled [Error: Unsupported function signature format.] Promise { <rejected> [Error: Unsupported function signature format.] }
/usr/local/lib/node_modules/canonical/dist/bin/index.js:35
    throw reason;
    ^

Error: Unsupported function signature format.
    at /usr/local/lib/node_modules/canonical/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:35:15
    at arrayMap (/usr/local/lib/node_modules/canonical/node_modules/lodash/internal/arrayMap.js:16:21)
    at map (/usr/local/lib/node_modules/canonical/node_modules/lodash/collection/map.js:65:10)
    at Object.getFunctionParameterNames (/usr/local/lib/node_modules/canonical/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:26:30)
    at /usr/local/lib/node_modules/canonical/node_modules/eslint-plugin-jsdoc/dist/rules/checkParamNames.js:89:51
    at EventEmitter.checkJsdoc (/usr/local/lib/node_modules/canonical/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:32:13)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/canonical/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/usr/local/lib/node_modules/canonical/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
```

**Comment by gajus** [comment]
What is the actual function? This error refers to the function parameters, not the JSDoc block.

**Comment by bitspook** [comment]
Removing the above given block of jsdoc solves this error.

``` js
/**
 * Make geolocation for `lat` and `lng` coordinates.
 * Reverse geocoding is an asynchronous operation, so this function returns a Promise.
 *
 * @param {Object} latLng
 * @property {number} lat
 * @property {number} lng
 *
 * @returns {Promise}
 */
export default ({latitude, longitude}) => {
    return new Promise((resolve, reject) => {
        let geocoder,
            geolocation;

        geolocation = {
            coordinates: {
                latitude,
                longitude
            },
            country: {
                code: 'oo'
            }
        };

        return resolve(geolocation);
  });
}
```

**Comment by gajus** [comment]
`@property` does not belong in a Function block. It would make sense if written such as:

``` js
/**
 * @typedef {Object} coordinates
 * @property {number} latitude
 * @property {number} longitude
 */

/**
 * @param {coordinates} coordinates
 * @returns {Promise}
 */
```

You can keen the declaration to one line using `@param` with a path (as you do with `@property`) at the moment (as documented here http://usejsdoc.org/tags-param.html#parameters-with-properties).

**Comment by gajus** [comment]
However, the error is because https://github.com/gajus/eslint-plugin-jsdoc does not support destruction in the function parameters.

**Comment by gajus** [comment]
Regardless, this is an issue with https://github.com/gajus/eslint-plugin-jsdoc

**Comment by bitspook** [comment]
This issue is still causing lot of annoyance. It's still happening for functions which use argument destructuring and have any kind of jsdoc.
